name: Python Quality Checks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install ruff mypy
        if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt; fi
        
    - name: Run code formatting
      run: make fmt
      
    - name: Run type checking
      run: make mypy
      
    - name: Run tests
      run: make test
